// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxpqqnrlidnhrcagvrwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cHFxbnJsaWRuaHJjYWd2cndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDg4MzEsImV4cCI6MjA3NDUyNDgzMX0.u9zCBpokJYI5yogSjv4bVHMfGoh9ATa22BZrpqVCV8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});